### ISSUE TITLE
Start comments with Uppercase letter.

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-app-zendesk#76]
Also noticed a lot of sentences here are started with a lowercase letter. Probably not a big deal because they're comments, but I think we consistently start comments with a capital letter in our projects, especially if it's a sentence. This doesn't apply to sentences that start with a lowercase function name.

```suggestion
// Conditions are fetched only once when the modal opens and stores in state.
```

_Originally posted by @mickmister in https://github.com/mattermost/mattermost-app-zendesk/pull/74#discussion_r696179430_

**Comment by adithyaakrishna** [comment]
I would love to take this up 👀
