### ISSUE TITLE
Use Mattermost eslint rules.

### ISSUE THREAD

**Issue by jfrerich** [mattermost/mattermost-app-zendesk#77]
I assume some of these are removed because they are not used. Is there a lint-like(or other tool) that we can use to detect unused vars?

_Originally posted by @catalintomai in https://github.com/mattermost/mattermost-app-zendesk/pull/74#discussion_r702463496_

**Comment by jfrerich** [comment]
This is included in the mattermost-webapp package.json https://github.com/mattermost/eslint-plugin-mattermost. The `.eslintrc.json` files from Mattermost and this app should be compared to determine a consistent style guide.

**Comment by jfrerich** [comment]
Fix the following with the PR for this issue.
![image](https://user-images.githubusercontent.com/7575921/132358542-53f90e74-ff3b-4f82-b1a5-ce5a547a09ef.png)

**Comment by adithyaakrishna** [comment]
I would like to work on this 👀

**Comment by jfrerich** [comment]
@adithyaakrishna, can you add this rule as PR to this file https://github.com/mattermost/mattermost-app-zendesk/blob/master/.eslintrc.json?  

After adding the rule, you should be able to run `npm run fix` to trigger eslint to fix the changes for you :) 

I do like that you have created [this PR](https://github.com/mattermost/eslint-plugin-mattermost/pull/5) in the `eslint-mattermost-plugin` repo, but I am not referencing that repo at the moment.
